name: deploy gh-pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v2.3.1

      - name: deploy  
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: .
